services:
  - type: web
    name: ficha-ordem
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/ficha-0.0.1-SNAPSHOT.jar --spring.profiles.active=production
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ficha-db
          property: connectionString
      - key: DB_USER
        fromDatabase:
          name: ficha-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ficha-db
          property: password

databases:
  - name: ficha-db
    databaseName: ficha_db
    user: ficha_user
    plan: free

